{
  Exception e=new TestException();
  assertEquals(Utils.returnFirstExceptionIfInListOrThrowStandardExceptionOrCause(new Class[]{TestException.class},e),e);
  assertEquals(Utils.returnFirstExceptionIfInListOrThrowStandardExceptionOrCause(new Class[]{TestException.class},new RuntimeException(e)),e);
}
