{
  if (e.getCause() instanceof Exception) {
    logger.debug("Processing exception for: %s",e.getCause());
    T returnVal=function.apply((Exception)e.getCause());
    logger.debug("Processed exception for: %s",e.getCause());
    if (returnVal != null)     return returnVal;
  }
  throw e;
}
