{
  logger.warn(e,"exception in rendezvous: %s",rendezvous);
  try {
    rendezvous.setException(e);
  }
 catch (  InterruptedException e1) {
    logger.error(e,"interrupted setting exception on command",rendezvous);
  }
}
