{
  Function<Exception,Object> function=new ReturnAbiquoExceptionOnNotFoundOr4xx();
  ResourceNotFoundException exception=new ResourceNotFoundException();
  try {
    function.apply(exception);
  }
 catch (  Exception ex) {
    assertEquals(ex,exception);
  }
}
