{
  Exception e=new ResourceNotFoundException();
  assertEquals(Utils.returnFirstExceptionIfInListOrThrowStandardExceptionOrCause(new Class[]{},new RuntimeException(e)),e);
}
