{
  Throwable exception=Iterables.find(Throwables.getCausalChain(from),isNotFoundAndHasAbiquoException(from),null);
  throw Throwables.propagate(exception == null ? from : (AbiquoException)exception.getCause());
}
