{
  fn.handleError(command,retryAt);
  assertEquals(command.getException().getClass(),RetryAfterException.class);
  assertEquals(command.getException().getMessage(),"retry in 3600 seconds");
}
