{
  if (e.getCause() instanceof Exception) {
    T returnVal=function.apply((Exception)e.getCause());
    if (returnVal != null)     return returnVal;
  }
  throw e;
}
