{
  Throwable exception=find(getCausalChain(from),isNotFoundAndHasAbiquoException(from),null);
  throw propagate(exception == null ? from : exception.getCause());
}
